# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import FMS_pb2 as FMS__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in FMS_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManagementServiceStub(object):
    """The FMS service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitEvent = channel.unary_unary(
                '/com.distributedFMS.ManagementService/SubmitEvent',
                request_serializer=FMS__pb2.SubmitEventRequest.SerializeToString,
                response_deserializer=FMS__pb2.SubmitEventResponse.FromString,
                _registered_method=True)


class ManagementServiceServicer(object):
    """The FMS service definition.
    """

    def SubmitEvent(self, request, context):
        """Submits an event to the FMS.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitEvent,
                    request_deserializer=FMS__pb2.SubmitEventRequest.FromString,
                    response_serializer=FMS__pb2.SubmitEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.distributedFMS.ManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.distributedFMS.ManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManagementService(object):
    """The FMS service definition.
    """

    @staticmethod
    def SubmitEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.distributedFMS.ManagementService/SubmitEvent',
            FMS__pb2.SubmitEventRequest.SerializeToString,
            FMS__pb2.SubmitEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AlarmServiceStub(object):
    """The Alarm Query service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryAlarms = channel.unary_stream(
                '/com.distributedFMS.AlarmService/QueryAlarms',
                request_serializer=FMS__pb2.QueryAlarmsRequest.SerializeToString,
                response_deserializer=FMS__pb2.AlarmMessage.FromString,
                _registered_method=True)


class AlarmServiceServicer(object):
    """The Alarm Query service definition.
    """

    def QueryAlarms(self, request, context):
        """Queries for alarms, with optional filtering.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlarmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryAlarms': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryAlarms,
                    request_deserializer=FMS__pb2.QueryAlarmsRequest.FromString,
                    response_serializer=FMS__pb2.AlarmMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.distributedFMS.AlarmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.distributedFMS.AlarmService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlarmService(object):
    """The Alarm Query service definition.
    """

    @staticmethod
    def QueryAlarms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.distributedFMS.AlarmService/QueryAlarms',
            FMS__pb2.QueryAlarmsRequest.SerializeToString,
            FMS__pb2.AlarmMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TopologyServiceStub(object):
    """============================================================================
    TOPOLOGY LEARNING SERVICE (GNN-based)
    ============================================================================

    The Topology Learning service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrainTopology = channel.unary_unary(
                '/com.distributedFMS.TopologyService/TrainTopology',
                request_serializer=FMS__pb2.TrainTopologyRequest.SerializeToString,
                response_deserializer=FMS__pb2.TrainTopologyResponse.FromString,
                _registered_method=True)
        self.TrainTopologyWithAlarms = channel.unary_unary(
                '/com.distributedFMS.TopologyService/TrainTopologyWithAlarms',
                request_serializer=FMS__pb2.TrainTopologyRequestWithAlarms.SerializeToString,
                response_deserializer=FMS__pb2.TrainTopologyResponse.FromString,
                _registered_method=True)
        self.GetTopology = channel.unary_unary(
                '/com.distributedFMS.TopologyService/GetTopology',
                request_serializer=FMS__pb2.GetTopologyRequest.SerializeToString,
                response_deserializer=FMS__pb2.GetTopologyResponse.FromString,
                _registered_method=True)
        self.PredictConnection = channel.unary_unary(
                '/com.distributedFMS.TopologyService/PredictConnection',
                request_serializer=FMS__pb2.PredictConnectionRequest.SerializeToString,
                response_deserializer=FMS__pb2.PredictConnectionResponse.FromString,
                _registered_method=True)
        self.GetDeviceConnections = channel.unary_unary(
                '/com.distributedFMS.TopologyService/GetDeviceConnections',
                request_serializer=FMS__pb2.GetDeviceConnectionsRequest.SerializeToString,
                response_deserializer=FMS__pb2.GetDeviceConnectionsResponse.FromString,
                _registered_method=True)


class TopologyServiceServicer(object):
    """============================================================================
    TOPOLOGY LEARNING SERVICE (GNN-based)
    ============================================================================

    The Topology Learning service definition.
    """

    def TrainTopology(self, request, context):
        """Train the GNN model from alarm history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainTopologyWithAlarms(self, request, context):
        """Train with real alarms from Ignite (NEW)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopology(self, request, context):
        """Get the current learned topology
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictConnection(self, request, context):
        """Predict if two devices are connected
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceConnections(self, request, context):
        """Get predicted edges for a specific device
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TopologyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrainTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainTopology,
                    request_deserializer=FMS__pb2.TrainTopologyRequest.FromString,
                    response_serializer=FMS__pb2.TrainTopologyResponse.SerializeToString,
            ),
            'TrainTopologyWithAlarms': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainTopologyWithAlarms,
                    request_deserializer=FMS__pb2.TrainTopologyRequestWithAlarms.FromString,
                    response_serializer=FMS__pb2.TrainTopologyResponse.SerializeToString,
            ),
            'GetTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopology,
                    request_deserializer=FMS__pb2.GetTopologyRequest.FromString,
                    response_serializer=FMS__pb2.GetTopologyResponse.SerializeToString,
            ),
            'PredictConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictConnection,
                    request_deserializer=FMS__pb2.PredictConnectionRequest.FromString,
                    response_serializer=FMS__pb2.PredictConnectionResponse.SerializeToString,
            ),
            'GetDeviceConnections': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceConnections,
                    request_deserializer=FMS__pb2.GetDeviceConnectionsRequest.FromString,
                    response_serializer=FMS__pb2.GetDeviceConnectionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.distributedFMS.TopologyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.distributedFMS.TopologyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TopologyService(object):
    """============================================================================
    TOPOLOGY LEARNING SERVICE (GNN-based)
    ============================================================================

    The Topology Learning service definition.
    """

    @staticmethod
    def TrainTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.distributedFMS.TopologyService/TrainTopology',
            FMS__pb2.TrainTopologyRequest.SerializeToString,
            FMS__pb2.TrainTopologyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainTopologyWithAlarms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.distributedFMS.TopologyService/TrainTopologyWithAlarms',
            FMS__pb2.TrainTopologyRequestWithAlarms.SerializeToString,
            FMS__pb2.TrainTopologyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.distributedFMS.TopologyService/GetTopology',
            FMS__pb2.GetTopologyRequest.SerializeToString,
            FMS__pb2.GetTopologyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.distributedFMS.TopologyService/PredictConnection',
            FMS__pb2.PredictConnectionRequest.SerializeToString,
            FMS__pb2.PredictConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceConnections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.distributedFMS.TopologyService/GetDeviceConnections',
            FMS__pb2.GetDeviceConnectionsRequest.SerializeToString,
            FMS__pb2.GetDeviceConnectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
