# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import topology_pb2 as topology__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in topology_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TopologyServiceStub(object):
    """Topology Learning Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrainTopology = channel.unary_unary(
                '/topology.TopologyService/TrainTopology',
                request_serializer=topology__pb2.TrainRequest.SerializeToString,
                response_deserializer=topology__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.GetTopology = channel.unary_unary(
                '/topology.TopologyService/GetTopology',
                request_serializer=topology__pb2.GetTopologyRequest.SerializeToString,
                response_deserializer=topology__pb2.GetTopologyResponse.FromString,
                _registered_method=True)
        self.PredictConnection = channel.unary_unary(
                '/topology.TopologyService/PredictConnection',
                request_serializer=topology__pb2.ConnectionRequest.SerializeToString,
                response_deserializer=topology__pb2.ConnectionResponse.FromString,
                _registered_method=True)
        self.StreamTopologyUpdates = channel.unary_stream(
                '/topology.TopologyService/StreamTopologyUpdates',
                request_serializer=topology__pb2.StreamRequest.SerializeToString,
                response_deserializer=topology__pb2.TopologyUpdate.FromString,
                _registered_method=True)


class TopologyServiceServicer(object):
    """Topology Learning Service
    """

    def TrainTopology(self, request, context):
        """Train the GNN model from alarm history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopology(self, request, context):
        """Get the current learned topology
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictConnection(self, request, context):
        """Predict if two devices are connected
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTopologyUpdates(self, request, context):
        """Stream real-time topology updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TopologyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrainTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainTopology,
                    request_deserializer=topology__pb2.TrainRequest.FromString,
                    response_serializer=topology__pb2.TrainResponse.SerializeToString,
            ),
            'GetTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopology,
                    request_deserializer=topology__pb2.GetTopologyRequest.FromString,
                    response_serializer=topology__pb2.GetTopologyResponse.SerializeToString,
            ),
            'PredictConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictConnection,
                    request_deserializer=topology__pb2.ConnectionRequest.FromString,
                    response_serializer=topology__pb2.ConnectionResponse.SerializeToString,
            ),
            'StreamTopologyUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTopologyUpdates,
                    request_deserializer=topology__pb2.StreamRequest.FromString,
                    response_serializer=topology__pb2.TopologyUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'topology.TopologyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('topology.TopologyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TopologyService(object):
    """Topology Learning Service
    """

    @staticmethod
    def TrainTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/topology.TopologyService/TrainTopology',
            topology__pb2.TrainRequest.SerializeToString,
            topology__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/topology.TopologyService/GetTopology',
            topology__pb2.GetTopologyRequest.SerializeToString,
            topology__pb2.GetTopologyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/topology.TopologyService/PredictConnection',
            topology__pb2.ConnectionRequest.SerializeToString,
            topology__pb2.ConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTopologyUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/topology.TopologyService/StreamTopologyUpdates',
            topology__pb2.StreamRequest.SerializeToString,
            topology__pb2.TopologyUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
